config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destory'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :users
  resources :reviews
  
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :review_category_relations, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  
  mount_uploader :myimage, ImageUploader
  
  before_save { self.email.downcase! }
  validates :name, presence: { message: "を入力してください"}, length: { message: "10字以内で入力してください", maximum: 10 }
  validates :email, presence: { message: "を入力してください"}, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  validates :profile, length: { message: "200字以内で入力してください", maximum: 200 }
  
  has_secure_password
  
  has_many :reviews
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites
  has_many :favoreview, through: :favorites, source: :review
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def like(review)
    favorites.find_or_create_by(review_id: review.id)
  end

  
  def unlike(review)
    favorite = favorites.find_by(review_id: review.id)
    favorite.destroy if favorite
  end

  
  def favoreview?(review)
    self.favoreview.include?(review)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update, :destory, :followings, :followers, :likes]
  before_action :correct_user, only: [:edit, :update, :destory]
  
  
  def index
    
  end
  
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.order(id: :desc)
    counts(@user) 
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user=User.new(user_params)
    if @user.save
      flash[:success] = "新規ユーザー登録しました"
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:danger] = "ユーザーの登録に失敗しました"
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'ユーザー情報は更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報は更新されませんでした'
      render :edit
    end
  end
  
  def destory
  end

  def followings
    @user = User.find(params[:id])
    @followings = @user.followings
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
    counts(@user)
  end


  def likes
    @user = User.find(params[:id])
    @favoreview = @user.favoreview
    counts(@user)
  end

  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :myimage)
  end
  
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
  end
  
  
  
end

app/views/users/_userprofile.html.erb
<div class="profile-box">
<%= link_to '一覧に戻る', reviews_path %>


    
 
    <div>
      <div class="user-name">
        <% if user.myimage? %>
          <%= image_tag user.myimage.thumb100.url, class: 'myimage'  %>
        <% end %>
    
        <span>  <%= user.name %>  さんのページ</span>
       </div>
       
       <% if logged_in? %>
       <div class='profile-btn'>
           <% if current_user == user %>
           <%= link_to 'レビュー投稿', new_review_path, class: 'btn btn btn-warning' %>
            <%= link_to 'プロフィール編集', edit_user_path(user), class: 'btn  btn-secondary' %>
            
          
          <% else %>
            <%= render 'relationships/follow_button', user: @user %>
          <% end %>
        
          <% end %>
       </div>
       
       
       <div class='user-profile'><p>【プロフィール】</p><%= simple_format(user.profile) %></div>
      
   </div> 
 
  

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <div class="user-box">
          
            <% if user.myimage? %>
            
              <%= image_tag user.myimage.thumb50.url, class: 'myimage' %>
            
            <% end %>
            
            <%= user.name %>
          <p>【プロフィール】<%= user.profile %></p>
          <p><%= link_to 'ユーザーページ', user_path(user) %></p>

        </div>
      </li>
    <% end %>
  </ul>
  
<% end %>

app/views/users/edit.html.erb
<div class="container">
<h1><%= @user.name %> のプロフィール編集ページ</h1>

<%= form_with(model: @user, local: true) do |f| %>
  
  <% if @user.errors.any? %>
    
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
   
      <% end %>
  <div class="form-group">
  
  <%= f.label :name, '【名前】' %>
  <%= f.text_field :name, class: 'form-control', rows: 1 %> 
  
  <%= f.label :email, '【メール】' %>
  <%= f.text_field :email, class: 'form-control', rows: 1 %>
  
  <%= f.label :profile, '【プロフィール文】' %>
  <%= f.text_area :profile, class: 'form-control', rows: 4 %>
  <%= f.label "【アイコン画像をアップロード】" %><br><%= f.file_field :myimage, class: "btn btn-outline-secondary" %>


  <%= f.submit '編集を保存', class: 'btn btn-primary' %>
<% end %>

</div>
</div>

app/views/users/followers.html.erb
 <%= render 'users/userprofile', user: @user %>

  <div class="container">
    <ul class="nav nav-tabs nav-justified mb-3">
      
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">レビュー <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り <span class="badge badge-secondary"><%= @count_favoreview %></span></a></li>
    </ul>
   <%= render 'users', users: @followers %>
  </div>
    
</div>

app/views/users/followings.html.erb
   <%= render 'users/userprofile', user: @user %>
  
  <div class="container">
    <ul class="nav nav-tabs nav-justified mb-3">
      
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">レビュー <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り <span class="badge badge-secondary"><%= @count_favoreview %></span></a></li>
    </ul>
   <%= render 'users', users: @followings %>
  </div>
    
</div>

app/views/users/likes.html.erb
 <%= render 'users/userprofile', user: @user %>
 

    <ul class="nav nav-tabs nav-justified mb-3">
      
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">レビュー <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り <span class="badge badge-secondary"><%= @count_favoreview %></span></a></li>
    </ul>
   <%= render 'reviews/reviews', reviews: @favoreview %>

    

app/views/users/new.html.erb
<div class="container">

<div class="text-center">
  <h1>新規ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    
    

      <% if @user.errors.any? %>
    
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
   
      <% end %>
    
    
    
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
    
    <p>ログインは <%= link_to 'こちら', login_path %></p>
  </div>
</div>
</div>

app/views/users/show.html.erb
 <div class="container">
 <%= render 'users/userprofile', user: @user %>
  

    <ul class="nav nav-tabs nav-justified mb-3">
      
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">レビュー <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り <span class="badge badge-secondary"><%= @count_favoreview %></span></a></li>
    </ul>
    
   <%= render 'reviews/reviews', reviews: @reviews %>
</div>