config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destory'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :users
  resources :reviews
  
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :review_category_relations, only: [:create, :destroy]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  
  has_many :review_category_relations, dependent: :destroy
  has_many :categories, through: :review_category_relations
  
  mount_uploader :image, ImageUploader
  
  
  validates :title, presence: { message: "は必ず入力してください"}, length: { message: "25字以内で入力してください", maximum: 25}
  validates :content, presence: { message: "は必ず入力してください"}, length: {message: "1000字以内で入力してください", maximum: 1000}
  validates :point, presence: { message: "は必ず入力してください" }, numericality: { message: "0から100(半角)の整数で入力してください", greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  
  has_many :favorites, foreign_key: 'review_id', dependent: :destroy
  has_many :users, through: :favorites
  
  def self.search(search)
    if search
      Review.where(['title LIKE ?', "%#{search}%"])
    else
      Review.all
    end
  end
  
  
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :edit, :update, :destory]
  before_action :correct_user, only: [:edit, :update, :destory]
  
  PER =
  
  def index
    @reviews = Review.all.page(params[:page]).per(15).order(created_at: :desc).search(params[:search])
    # @reviews = Review.all.page(params[:page]).per(8)
    # @fav_lists = Favorite.group(:review_id).order('count_all desc').count
    # @reviews = Review.find(@fav_lists.keys)
    
  end

  def show
    @review = Review.find(params[:id])

  end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      flash[:success] = 'レビューを投稿しました。'
      redirect_to reviews_path
    else
      @reviews = current_user.reviews.order(id: :desc)
      flash.now[:danger] = 'レビューの投稿に失敗しました。'
      render 'new'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
     @review = Review.find(params[:id])

    if @review.update(review_params)
      flash[:success] = 'レビューが更新されました'
      redirect_to @review
    else
      flash.now[:danger] = 'レビューは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    flash[:success] = 'レビューが削除されました'
    redirect_to reviews_url
  end
  
  
  def search
      @reviews = Review.search(params[:search])
 
  end

private

  def review_params
    params.require(:review).permit(:title, :content, :point, :image, category_ids: [] )
  end
  
  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
  
end

app/views/reviews/_reviews.html.erb
<% reviews.each do |review| %>
  
  <div class='row review-box'>

    <div class='review-box-main col-md-8 col-sm-6'>
      <div class='review-user-name'>
        <% if review.user.myimage? %>
          <%= image_tag review.user.myimage.thumb50.url, class: 'myimage' %>
        <% end %>
        <a href="<%= user_path(review.user) %>"><%= review.user.name %></a>
      </div>
      
      <div class='review-title'>
        <a href="<%= review_path(review) %>"><%= review.title %></a>
      </div>
      
      <div class="review-list">
      <span>【カテゴリ】</span>
      <% review.categories.each do |category| %>
        <%= category.name %>,
      <% end %>
      
      <p><span>【評価】</span> <%= review.point %>点</p> 
      
      
      
      
      <span>【レビュー詳細】</span>
      <div class='box-review-content'><%= simple_format(review.content) %></div>
     
     
     
    
      <p><span>【お気に入り】</span><span style='color: red;'><%= review.favorites.count %></span> 件</p>
      
      <% if logged_in? %>
      
          <%= render 'favorites/like_button', review: review %>
      
        <% end %>
        </div>
    </div>
    
    
   
    <div class='col-md-4 col-sm-6'>
    <div class="text-right review-time"><%= review.created_at.strftime("%Y-%m-%d %H:%M") %> の投稿</div> 

      
      
      <div class="image-box text-center">
      <% if review.image? %>
        <%= image_tag review.image.url %>
        <% else %>
        <p>画像がありません</p>
      <% end %>
      </div>
      
    </div>
    
  </div>
<% end  %>
    
   
    

app/views/reviews/edit.html.erb
<div class="container">
<%= link_to '一覧に戻る', reviews_path %>

<h2>メッセージ編集ページ</h2>

<%= form_with(model: @review, local: true) do |f| %>
  <div class="form-group">
          <%= f.label :title, '【タイトル(最大25字)】' %>
          <%= f.text_field :title, class: 'form-control title-form', rows: 1 %> 
          
          <%= f.label :content, '【レビュー文(最大1000字)】' %>
          <%= f.text_area :content, class: 'form-control content-form', rows: 10 %>
          
          <%= f.label :point, '【評価点（0 ~ 100）】' %>
          <%= f.text_field :point, class: 'form-control point-form', rows: 1 %>
          <%= f.label "画像をアップロード" %><br><%= f.file_field :image %>
          
          <div class="margin-top-50">
          <%= f.label :category, '【カテゴリ(複数選択可)】' %><br>
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
            <%= category.label do %>
              <%= category.check_box %>
              <%= category.text %>
            <% end %>
          <% end %>
        </div>
  <div class="margin-bottom-50">        
  <%= f.submit '編集を保存', class: 'btn btn-primary' %>
  </div>
<% end %>

</div>
</div>

app/views/reviews/index.html.erb
<div class="container">

<h1 class="text-center">みんなのレビュー</h1>
<div class="text-center">
<% if logged_in? %>
  <%= link_to 'レビュー投稿', new_review_path, class: 'btn btn btn-warning' %>
<% else %>
  <h5><%= link_to 'ログイン', login_path %> してレビューを投稿する</h5>
<% end %>
</div>
<div class="search-box text-left">
<p>タイトル検索</p>
<%= form_tag(reviews_path, :method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil, class: "btn btn-info" %>
<% end %>

  </div>

  <% if @reviews.empty? %>
    <p style='margin-top: 20px'>検索結果が見つかりません</p>
    <%= link_to '一覧に戻る', reviews_path %>
  <% else %>
    <%= render 'reviews/reviews', reviews: @reviews, user: @user %>
  <% end %>

  
  
  <%= paginate @reviews %>
  <div class="text-center">
<% if logged_in? %>
  <%= link_to 'レビュー投稿', new_review_path, class: 'btn btn btn-warning' %>
<% else %>
  <h5><%= link_to 'ログイン', login_path %> してレビューを投稿する</h5>
<% end %>
</div>
  
  </div>

app/views/reviews/new.html.erb
<div class="container">
<%= link_to '一覧に戻る', reviews_path %>
<h2>新規レビュー投稿</h2>
<%= form_with(model: @review, local: true) do |f| %>
  <% if @review.errors.any? %>
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title, '【タイトル(最大25字)】' %>
    <%= f.text_field :title, class: 'form-control title-form', rows: 1 %> 
    <%= f.label :content, '【レビュー文(最大1000字)】' %>
    <%= f.text_area :content, class: 'form-control content-form', rows: 10 %>
          
    <%= f.label :point, '【評価点（0 ~ 100）】' %>
    <%= f.text_field :point, class: 'form-control point-form', rows: 1 %>
    <%= f.label "【画像をアップロード】" %><br><%= f.file_field :image, class:"btn btn-outline-secondary" %>
          
    <div class="margin-top-50">
      <%= f.label :category, '【カテゴリ(複数選択可)】' %><br>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
        <%= category.label do %>
          <%= category.check_box %>
          <%= category.text %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="margin-bottom-50">
  <%= f.submit 'レビューを投稿する', class: 'btn btn-primary' %>
 </div>
<% end %>
</div>

app/views/reviews/show.html.erb
<div class="container">
<%= link_to '一覧に戻る', reviews_path %>
<div class='row review-box'>
 <div class='review-box-main col-md-9'>
    <div class='review-user-name'>
      <% if @review.user.myimage? %>
        <%= image_tag @review.user.myimage.thumb100.url, class: 'myimage' %>
      <% end %>

      <a href="<%= user_path(@review.user) %>"><%= @review.user.name %></a>
  </div>
      <div class='review-title'><%= @review.title %></div>
      
      <div class="review-list">
          <span>【カテゴリ】</span>
          <% @review.categories.each do |category| %>
            <%= category.name %>,
          <% end %>
          <p><span>【評価】</span> <%= @review.point %>点</p>
        
        <span>【レビュー詳細】</span>
        <div class='review-content'><%= simple_format(@review.content) %></div>
        <p><span>【お気に入り】</span><span style='color: red;'><%= @review.favorites.count %></span> 件</p>
        <% if logged_in? %>
          <%= render 'favorites/like_button', review: @review %>

          <% if @review.user == current_user %>
            <%= link_to '編集する', edit_review_path(@review) %>
            <%= link_to '削除する', @review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
          <% end %>
      <% end %>
        
      </div>
      
</div>


<aside class='col-md-3'>
  <div class='text-right'><%= @review.created_at.strftime("%Y-%m-%d %H:%M") %> の投稿</div> 
  
    <div class='image-box text-center'>
      <% if @review.image? %>
              <%= image_tag @review.image.url %>
      <% else %>
        <p>画像がありません</p>
      <% end %>
    </div>

</aside>
</div>
  </div>